/*
 * MIT License
 *
 * Copyright (c) 2016 Federico Vera <https://github.com/dktcoding>
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.dkt.mrft.gui;

import com.dkt.mrft.funcs.FunctionsRandom;
import com.dkt.mrft.models.DatasetTableModel;
import com.dkt.mrft.utils.BundleDecorator;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Random;
import java.util.ResourceBundle;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import net.objecthunter.exp4j.Expression;
import net.objecthunter.exp4j.ExpressionBuilder;
import net.objecthunter.exp4j.ValidationResult;
import net.objecthunter.exp4j.extras.FunctionsBoolean;
import net.objecthunter.exp4j.extras.FunctionsMisc;
import net.objecthunter.exp4j.extras.OperatorsComparison;

/**
 *
 * @author Federico Vera {@literal <fedevera at unc.edu.ar>}
 */
public final class FunctionGaussianRand extends JDialog {
    private static final BundleDecorator i18n = new BundleDecorator("res.i18n.dialogs");   
    
    private final MainWindow father;

    /**
     * Creates new form FunctionMonospaced
     * @param father
     */
    public FunctionGaussianRand(MainWindow father) {
        super((JFrame)null, true);
        this.father = father;
        initComponents();
        initListners();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jTextField1 = new JTextField();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jLabel6 = new JLabel();
        jFormattedTextField1 = new JFormattedTextField();
        jFormattedTextField2 = new JFormattedTextField();
        jFormattedTextField3 = new JFormattedTextField();
        jLabel7 = new JLabel();
        jFormattedTextField4 = new JFormattedTextField();
        jLabel8 = new JLabel();
        jFormattedTextField5 = new JFormattedTextField();
        jLabel10 = new JLabel();
        jFormattedTextField6 = new JFormattedTextField();

        ResourceBundle bundle = ResourceBundle.getBundle("res/i18n/dialogs"); // NOI18N
        setTitle(bundle.getString("F_GAUSS_RAND_TITLE")); // NOI18N

        jLabel1.setText(bundle.getString("F_GAUSS_RAND_FUNC")); // NOI18N

        jTextField1.setText("sin(x)");

        jLabel2.setIcon(new ImageIcon(getClass().getResource("/res/icons/warn.png"))); // NOI18N

        jLabel3.setText(bundle.getString("F_GAUSS_RAND_START")); // NOI18N

        jLabel4.setText(bundle.getString("F_GAUSS_RAND_END")); // NOI18N

        jLabel5.setText(bundle.getString("F_GAUSS_RAND_POINTS")); // NOI18N

        jButton1.setText(bundle.getString("F_GAUSS_RAND_GENERATE")); // NOI18N
        jButton1.setEnabled(false);
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(bundle.getString("F_GAUSS_RAND_CLOSE")); // NOI18N
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("%d puntos");

        jFormattedTextField1.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter()));
        jFormattedTextField1.setHorizontalAlignment(JTextField.CENTER);

        jFormattedTextField2.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));
        jFormattedTextField2.setHorizontalAlignment(JTextField.CENTER);

        jFormattedTextField3.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter()));
        jFormattedTextField3.setHorizontalAlignment(JTextField.CENTER);

        jLabel7.setText(bundle.getString("F_GAUSS_RAND_SEED")); // NOI18N

        jFormattedTextField4.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));

        jLabel8.setText(bundle.getString("F_GAUSS_RAND_AVERAGE")); // NOI18N

        jFormattedTextField5.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter()));
        jFormattedTextField5.setHorizontalAlignment(JTextField.CENTER);

        jLabel10.setText(bundle.getString("F_GAUSS_RAND_VARIANCE")); // NOI18N

        jFormattedTextField6.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter()));
        jFormattedTextField6.setHorizontalAlignment(JTextField.CENTER);
        jFormattedTextField6.setText("1");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextField1, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField3, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextField5, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField6, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jFormattedTextField4))))
                .addContainerGap())
        );

        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {jButton1, jButton2});

        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jFormattedTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jFormattedTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean out;
    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        out = false;
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        out = true;
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButton2;
    private JFormattedTextField jFormattedTextField1;
    private JFormattedTextField jFormattedTextField2;
    private JFormattedTextField jFormattedTextField3;
    private JFormattedTextField jFormattedTextField4;
    private JFormattedTextField jFormattedTextField5;
    private JFormattedTextField jFormattedTextField6;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void initListners() {
        DocumentListener dl = new DocumentListener() {
            @Override public void insertUpdate(DocumentEvent e) {
                jButton1.setEnabled(checkInterval() && validateFunc());
            }

            @Override public void removeUpdate(DocumentEvent e) {
                jButton1.setEnabled(checkInterval() && validateFunc());
            }

            @Override public void changedUpdate(DocumentEvent e) {
                jButton1.setEnabled(checkInterval() && validateFunc());
            }
        };
        
        jTextField1.getDocument().addDocumentListener(dl);
        jFormattedTextField1.getDocument().addDocumentListener(dl);
        jFormattedTextField2.getDocument().addDocumentListener(dl);
        jFormattedTextField3.getDocument().addDocumentListener(dl);
        jFormattedTextField4.getDocument().addDocumentListener(dl);
        jFormattedTextField5.getDocument().addDocumentListener(dl);
        jFormattedTextField6.getDocument().addDocumentListener(dl);
        
        jTextField1.setText("if(x == 0, 1, sin(x) / x)");
        jFormattedTextField1.setValue(-3);
        jFormattedTextField3.setValue(3);
        jFormattedTextField2.setValue(20);
        jFormattedTextField4.setValue(System.nanoTime());
        jFormattedTextField5.setValue(0.0);
        jFormattedTextField6.setValue(1.0);
    }
    
    private boolean checkInterval() {
        try {
            jFormattedTextField1.commitEdit();
            jFormattedTextField2.commitEdit();
            jFormattedTextField3.commitEdit();
            jFormattedTextField4.commitEdit();
            jFormattedTextField5.commitEdit();
            jFormattedTextField6.commitEdit();
        } catch (ParseException ignoreMe) {
            jLabel6.setText(i18n.__("F_GAUSS_RAND_INVALID"));
            return false;
        }
        
        double start = ((Number)jFormattedTextField1.getValue()).doubleValue();
        double end   = ((Number)jFormattedTextField3.getValue()).doubleValue();
        int    nval  = ((Number)jFormattedTextField2.getValue()).intValue();
        double mean  = ((Number)jFormattedTextField5.getValue()).doubleValue();
        double var   = ((Number)jFormattedTextField6.getValue()).doubleValue();
        boolean status = start < end && nval > 0;   
        status = status && mean >= start && mean <= end;
        status = status && var > 0;
        
        if (!status) {
            jLabel6.setText(i18n.__("F_GAUSS_RAND_INVALID"));
        } else {
            jLabel6.setText("");
        }
        
        return status;
    }

    private final ImageIcon warn = new ImageIcon(getClass().getResource("/res/icons/warn.png"));
    private final ImageIcon a_ok = new ImageIcon(getClass().getResource("/res/icons/a_ok.png"));
    private boolean validateFunc() {
        String expString = jTextField1.getText();
        if (expString.trim().isEmpty()) {
            jLabel2.setIcon(warn);
            return false;
        }
        try {
            ExpressionBuilder exp = new ExpressionBuilder(expString).variable("x");
            exp.functions(FunctionsMisc.getFunctions());
            exp.functions(FunctionsBoolean.getFunctions());
            exp.functions(FunctionsRandom.getFunctions());
            exp.operator (OperatorsComparison.getOperators());
            Expression e = exp.build().setVariable("x", 1);
            ValidationResult vr = e.validate();
            if (vr.isValid()) {
                jLabel2.setIcon(a_ok);
                jLabel2.setToolTipText("");
            } else {
                jLabel2.setToolTipText(i18n.__("F_GAUSS_RAND_EXP"));
                jLabel2.setIcon(warn);
                return false;
            }
        } catch (Exception ex) {
            jLabel2.setToolTipText(ex.getMessage());
            jLabel2.setIcon(warn);
            return false;
        }
        return true;
    }

    public ArrayList<DatasetTableModel.Row> getData() {
        if (!out) {
            return new ArrayList<>(0);
        }
        
        double start = ((Number)jFormattedTextField1.getValue()).doubleValue();
        double end   = ((Number)jFormattedTextField3.getValue()).doubleValue();
        int    nval  = ((Number)jFormattedTextField2.getValue()).intValue();
        long   seed  = ((Number)jFormattedTextField4.getValue()).longValue();
        double mean  = ((Number)jFormattedTextField5.getValue()).doubleValue();
        double var   = ((Number)jFormattedTextField6.getValue()).doubleValue();
        
        ArrayList<DatasetTableModel.Row> ret = new ArrayList<>(nval);
        
        String expString = jTextField1.getText();
        try {
            ExpressionBuilder exp = new ExpressionBuilder(expString).variable("x");
            exp.functions(FunctionsBoolean.getFunctions());
            exp.functions(FunctionsMisc.getFunctions());
            exp.functions(FunctionsRandom.getFunctions());
            exp.operator (OperatorsComparison.getOperators());
            Expression f = exp.build(true);
            Random rand  = new Random(seed);
            for (int i = 0; i < nval; i++) {
                double x = rand.nextGaussian() * var + mean;
                if (x < start || x > end) {
                    i++;
                    continue;
                }
                ret.add(new DatasetTableModel.Row(false, x, f.setVariable("x", x).evaluate()));
            }
            father.info(
                "Evaluating: '%s' in [%f,%f] with %d random gaussian points N(%f, %f) and seed = %d", 
                expString, start, end, nval, mean, var, seed
            );
        } catch (Exception ex) {
            father.error(
                "Error evaluating: '%s' in [%f,%f] with %d random gaussian points N(%f, %f) and seed = %d (%s)", 
                expString, start, end, nval, mean, var, seed, ex.getMessage()
            );
            jLabel2.setToolTipText(ex.getMessage());
            jLabel2.setIcon(warn);
        }
        
        return ret;
    }
}
